# PyTorch Basics for ML

In [7]:
import torch
import numpy as np

In [3]:
# Creating tensors in Pytorch
np.set_printoptions(precision=3)
a = [1,2,3]
b = np.array([4,5,6], dtype=np.int32)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a)
print(t_b)


tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [5]:
# ones
t_ones = torch.ones(2,3)
print(t_ones.shape)
print(t_ones)

torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
# random tensor values
rand_tensor = torch.rand(2,3)
print(rand_tensor)

tensor([[0.9985, 0.4663, 0.8064],
        [0.4845, 0.5810, 0.4140]])


## Manipulating the data type and shape of a tensor

In [8]:
# changing data type
t_a_new = t_a.to(torch.int64)
print(t_a_new.dtype)

torch.int64


In [9]:
# Transpose of a tensor
t = torch.rand(3,5)
t_tr = torch.transpose(t,0,1)
print(t.shape ,'--> ', t_tr.shape)

torch.Size([3, 5]) -->  torch.Size([5, 3])


In [11]:
# reshaping a tensor
t = torch.zeros(30)
print(t.shape)
t_reshape = t.reshape(5,6)
print(t_reshape.shape)

torch.Size([30])
torch.Size([5, 6])


In [13]:
# removing unnecessary dimensions
t = torch.zeros(1,2,1,4,1,)
t_sqz = torch.squeeze(t, 2)
print(t.shape, ' --> ', t_sqz.shape)

torch.Size([1, 2, 1, 4, 1])  -->  torch.Size([1, 2, 4, 1])


## Mathematical Operations to tensors

In [14]:
# uniform distribution and normal distribution
torch.manual_seed(1)
t1 = 2 * torch.rand(5,2) - 1
t2 = torch.normal(mean=0,std=1,size=(5,2)) 

In [16]:
print(t1)
print(t2)

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])
tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])


In [18]:
# t1 and t2 has the same shape. Element-wise product
t3 = torch.multiply(t1, t2)
print(t3)

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])


In [19]:
# mean, sum, and std across a certain axis
t4 = torch.mean(t1, dim=0)
print(t4)

tensor([-0.1373,  0.2028])


In [20]:
# matrix-matrix multiplication
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1))
print(t5)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])


In [21]:
t6 = torch.matmul(torch.transpose(t1, 0, 1), t2)
print(t6)

tensor([[ 1.7453,  0.3392],
        [-1.6038, -0.2180]])


In [22]:
# norm of a tensor
norm_t1 = torch.linalg.norm(t1, ord=2, dim=1)
print(norm_t1)

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])


## Split, stack and concatenate tensors

In [23]:
# providing number of splits
torch.manual_seed(1)
t = torch.rand(6)
print(t)
t_splits = torch.chunk(t, 3)
[item.numpy() for item in t_splits]

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999])


[array([0.758, 0.279], dtype=float32),
 array([0.403, 0.735], dtype=float32),
 array([0.029, 0.8  ], dtype=float32)]

In [24]:
# providing size of different splits
torch.manual_seed(1)
t = torch.rand(5)
print(t)
t_splits = torch.split(t, split_size_or_sections=[3,2])
[item.numpy() for item in t_splits]

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293])


[array([0.758, 0.279, 0.403], dtype=float32),
 array([0.735, 0.029], dtype=float32)]

In [25]:
# concatencate multiple tensors
A = torch.ones(3)
B = torch.zeros(2)
C = torch.cat([A, B], dim=0)
print(C)

tensor([1., 1., 1., 0., 0.])


In [26]:
# stack multiple tensors
A = torch.ones(3)
B = torch.zeros(3)
S = torch.stack([A,B], dim=1)
print(S)

tensor([[1., 0.],
        [1., 0.],
        [1., 0.]])


## Building input pipelines in PyTorch

If the data already exists in the form of a tensor object, a Python list, or a NumPy array, we can easily
create a dataset loader using the torch.utils.data.DataLoader() class. It returns an object of the
DataLoader class, which we can use to iterate through the individual elements in the input dataset.

In [27]:
from torch.utils.data import DataLoader
t = torch.arange(6, dtype=torch.float32)
data_loader = DataLoader(t)
for item in data_loader:
    print(item)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])
